const institutionMapping = {
    "Alberta": [
        "Alberta University of the Arts",
        "Ambrose University",
        "Athabasca University",
        "Bow Valley College",
        "Burman University",
        "Concordia University of Edmonton",
        "Northwestern Polytechnic",
        "Keyano College",
        "Lakeland College",
        "Lethbridge College",
        "MacEwan University",
        "Medicine Hat College",
        "NorQuest College",
        "Northern Lakes College",
        "Olds College",
        "St. Mary's University",
        "University of Alberta",
        "University of Calgary"
    ],
    "British Columbia": [
        "Camosun College",
        "Coast Mountain College",
        "College of New Caledonia",
        "College of the Rockies",
        "Douglas College",
        "Langara College",
        "North Island College",
        "Northern Lights College",
        "Okanagan College",
        "Selkirk College",
        "Vancouver Community College"
    ],
    "Manitoba": [
        "Booth University College",
        "Brandon University",
        "Canadian Mennonite University",
        "Providence University College",
        "University College of the North",
        "Université de Saint-Boniface",
        "University of Manitoba",
        "University of Winnipeg",
        "Assiniboine Community College",
        "École Technique et Professionnelle",
        "International College of Manitoba",
        "Manitoba Institute of Trades and Technology",
        "Red River College Polytech",
    ],
    "Newfoundland and Labrador": [
        "Administrator",
        "Computer Prorammer/Developer",
        "Engineer",
        "Executive",
        "IT Professional",
        "Manager",
        "Marketing/Sales",
        "Web Designer"
    ],
    "Ontario": [
        "Algoma University",
        "Brock University",
        "Carleton University",
        "Collège Universitaire Dominicain",
        "Lakehead University",
        "Laurentian University",
        "McMaster University",
        "Nipissing University",
        "OCAD University",
        "Ontario Tech University",
        "Queen's University",
        "Redeemer University",
        "Royal Military College of Canada",
        "Toronto Metropolitan University",
        "Trent University",
        "Université de Hearst",
        "University of Guelph",
        "University of Ottawa",
        "University of Toronto",
        "University of Waterloo",
        "University of Windsor",
        "Western University",
        "Wilfrid Laurier University",
        "York University"
    ],
    "Quebec": [
        "Cégep de l'Abitibi-Témiscamingue",
        "Collège Ahuntsic",
        "Collège d'Alma",
        "Cégep André-Laurendeau",
        "Cégep de Baie-Comeau",
        "Cégep Beauce-Appalaches",
        "Collège de Bois-de-Boulogne",
        "Champlain Regional College",
        "Saint Lambert Campus",
        "Saint Lawrence Campus",
        "Lennoxville Campus",
        "Cégep de Chicoutimi",
        "Dawson College",
        "Cégep de Drummondville",
        "Cégep Édouard-Montpetit",
        "École nationale d'aérotechnique",
        "Cégep Garneau",
        "Cégep de la Gaspésie et des Îles",
        "Collège Gérald-Godin",
        "Cégep de Granby-Haute-Yamaska",
        "Heritage College",
        "John Abbott College",
        "Cégep de Jonquière",
        "Cégep de La Pocatière",
        "Cégep régional de Lanaudière",
        "Joliette Campus",
        "L'Assomption Campus",
        "Terrebonne Campus",
        "Cégep de Lévis",
        "Cégep Limoilou",
        "Collège Lionel-Groulx",
        "Collège de Maisonneuve",
        "Cégep Marie-Victorin",
        "Cégep de Matane",
        "Collège Montmorency",
        "Cégep de l'Outaouais",
        "Cégep de Rimouski",
        "Cégep de Rivière-du-Loup",
        'Collège de Rosemont',
        "Cégep de Saint-Félicien",
        "Cégep de Saint-Hyacinthe",
        "Cégep de Saint-Jean-sur-Richelieu",
        "Cégep de Saint-Jérôme",
        "Cégep de Saint-Laurent",
        "Cégep de Sainte-Foy",
        "Cégep de Sept-Îles",
        "Collège Shawinigan",
        "Cégep de Sherbrooke",
        "Cégep de Sorel-Tracy",
        "Cégep de Thetford",
    ],
    "Saskatchewan": [
        "Bethany College",
        "Briercrest College and Seminary",
        "Carlton Trail College",
        "Horizon College and Seminary",
        "College Mathieu",
        "Cumberland College",
        "Eston College",
        "Great Plains College",
        "Lakeland College",
        "Nipawin Bible College",
        "North West College",
        "Northlands College",
        "Parkland College",
        "St Peter's College, Muenster",
        "Saskatchewan Indian Institute of Technologies",
        "Saskatchewan Polytechnic",
        "Southeast College",
        "Western Academy Broadcasting College"
    ]
}

const getProvinces = () => {
    return Object.keys(institutionMapping);
}

const getInstitutions = province => {
    return getInstitutions[province];
}

module.exports = { getProvinces, getInstitutions }